platform:
  security:
    enabled: false

ceph:
  http-endpoint: localhost:1000
  access-key: access-key
  secret-key: secret-key
  bucket: bucket-name

bpms:
  url: http://localhost:8100
form-management-provider:
  url: http://localhost:8082