bpms:
  url: http://localhost:8090
form-submission-validation:
  url: http://localhost:8088
remote-file-repository:
  url: http://localhost:8091

ceph:
  http-endpoint: localhost:1000
  access-key: access-key
  secret-key: secret-key
  bucket: bucket-name

digital-documents:
  max-file-size: 0.2MB
  max-total-file-size: 3.3MB

data-platform:
  kafka:
    bootstrap: ${spring.embedded.kafka.brokers}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      enabled: true
      custom-config:
        "[spring.serializer.key.delegate.class]": org.apache.kafka.common.serialization.StringSerializer
        "[spring.serializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonSerializer
        "[enable.idempotence]": true
    topic-properties:
      creation:
        enabled: true
        num-partitions: 2
        replication-factor: 1