bpms:
  url: http://localhost:8090
form-management-provider:
  url: http://localhost:8088

ceph:
  http-endpoint: localhost:1000
  access-key: access-key
  secret-key: secret-key
  bucket: bucket-name