kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: authotiz-policy-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  rules:
    - from:
        - source:
            notRequestPrincipals:
              - '*'
  action: DENY