apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  application.yml: |-
    server.max-http-header-size: 32KB
    spring.servlet.multipart.max-request-size: 50MB
    spring.servlet.multipart.max-file-size: 50MB
    ceph.http-endpoint: {{ .Values.ceph.host }}
    form-management-provider.url: http://form-management-provider:3001
    bpms.url: http://bpms:8080